import PDFDocument from 'pdfkit'

// ── Brand palette ─────────────────────────────────────────────────────────────
const ORANGE        = '#CD4419'
const ORANGE_LIGHT  = '#fdf3ef'
const ORANGE_BORDER = '#e8c5b0'
const DARK          = '#1a1a1a'
const GRAY_DARK     = '#444444'
const GRAY_MID      = '#6b6b6b'
const GRAY_LIGHT    = '#f4f2f0'
const GRAY_BORDER   = '#e0dbd6'
const WHITE         = '#ffffff'

const PAGE_W    = 612
const PAGE_H    = 792
const MARGIN    = 48
const CONTENT_W = PAGE_W - MARGIN * 2

function footer(doc) {
  const fy = PAGE_H - 38
  doc.moveTo(MARGIN, fy).lineTo(PAGE_W - MARGIN, fy)
    .strokeColor(GRAY_BORDER).lineWidth(0.5).stroke()
  doc.font('Helvetica').fontSize(7).fillColor(GRAY_MID)
    .text(
      'Generated by ADAS IQ  ·  Absolute ADAS  ·  absoluteadas.com  ·  ' +
      'Based on OEM position statements and ALLDATA ADAS procedures.',
      MARGIN, fy + 8, { width: CONTENT_W, align: 'center' }
    )
}

function contHeader(doc) {
  doc.rect(0, 0, PAGE_W, 36).fill(ORANGE)
  doc.roundedRect(MARGIN, 8, 22, 22, 4).fill(WHITE)
  doc.font('Helvetica-Bold').fontSize(9).fillColor(ORANGE).text('IQ', MARGIN, 14, { width: 22, align: 'center' })
  doc.font('Helvetica-Bold').fontSize(9).fillColor(WHITE).text('ADAS IQ', MARGIN + 28, 13)
  doc.font('Helvetica').fontSize(7.5).fillColor('rgba(255,255,255,0.75)')
    .text('Calibration Assessment Report — continued', MARGIN + 80, 14)
}

function pill(doc, x, y, text, bgColor, textColor) {
  const tw = doc.widthOfString(text, { fontSize: 7 }) + 14
  doc.roundedRect(x, y, tw, 15, 7.5).fill(bgColor)
  doc.font('Helvetica-Bold').fontSize(7).fillColor(textColor).text(text, x, y + 4.5, { width: tw, align: 'center' })
  return tw
}

function chip(doc, x, y, text, bgColor, textColor) {
  const tw = doc.widthOfString(text, { fontSize: 7 }) + 10
  doc.roundedRect(x, y, tw, 13, 3).fill(bgColor)
  doc.font('Helvetica').fontSize(7).fillColor(textColor).text(text, x + 5, y + 3.5)
  return tw
}

/**
 * Generate an ADAS IQ PDF report buffer.
 * @param {Object} jobData - { shop, ro_number, insurer, vin, vehicle, year, make, model, claim, calibrations, document_links }
 * @returns {Promise<Buffer>}
 */
export function generateADASIQPdf(jobData) {
  return new Promise((resolve, reject) => {
    const { shop, ro_number, insurer, vin, vehicle, year, make, model, claim, calibrations, document_links } = jobData

    const required = (calibrations || []).filter(c => c.enabled)
    const notReq   = (calibrations || []).filter(c => !c.enabled)

    const doc = new PDFDocument({ margin: 0, size: 'LETTER', autoFirstPage: true })
    const chunks = []
    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // ── PAGE 1 HEADER ─────────────────────────────────────────────────────
    doc.rect(0, 0, PAGE_W, 100).fill(ORANGE)
    doc.roundedRect(MARGIN, 22, 56, 56, 10).fill(WHITE)
    doc.font('Helvetica-Bold').fontSize(22).fillColor(ORANGE).text('IQ', MARGIN, 36, { width: 56, align: 'center' })
    doc.font('Helvetica-Bold').fontSize(24).fillColor(WHITE).text('ADAS IQ', MARGIN + 70, 28)
    doc.font('Helvetica').fontSize(11).fillColor('rgba(255,255,255,0.82)').text('Calibration Assessment Report', MARGIN + 70, 56)

    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    doc.font('Helvetica').fontSize(8).fillColor('rgba(255,255,255,0.65)')
      .text(dateStr, 0, 30, { width: PAGE_W - MARGIN, align: 'right' })
    if (ro_number) {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('rgba(255,255,255,0.9)')
        .text(`RO# ${ro_number}`, 0, 46, { width: PAGE_W - MARGIN, align: 'right' })
    }

    let y = 118

    // ── VEHICLE INFO CARD ──────────────────────────────────────────────────
    const vehicleStr = [year, make, model].filter(Boolean).join(' ') || vehicle || '—'
    doc.roundedRect(MARGIN, y, CONTENT_W, 120, 8).fill(GRAY_LIGHT)
    doc.roundedRect(MARGIN, y, CONTENT_W, 120, 8).stroke(GRAY_BORDER).lineWidth(0.5)
    doc.roundedRect(MARGIN, y, 4, 120, 2).fill(ORANGE)
    doc.font('Helvetica-Bold').fontSize(15).fillColor(DARK).text(vehicleStr, MARGIN + 16, y + 14, { width: CONTENT_W - 32 })
    if (vin) {
      doc.font('Helvetica').fontSize(8).fillColor(GRAY_MID).text(`VIN  ${vin}`, MARGIN + 16, y + 36)
    }
    const ruleY = y + (vin ? 52 : 44)
    doc.moveTo(MARGIN + 16, ruleY).lineTo(MARGIN + CONTENT_W - 16, ruleY)
      .strokeColor(GRAY_BORDER).lineWidth(0.5).stroke()

    const detailFields = [['SHOP', shop], ['RO NUMBER', ro_number], ['INSURER', insurer], ['CLAIM #', claim]].filter(([, v]) => v)
    const colW = CONTENT_W / 4
    detailFields.forEach(([label, value], i) => {
      const fx = MARGIN + 16 + i * colW
      const fy = ruleY + 10
      doc.font('Helvetica').fontSize(7).fillColor(GRAY_MID).text(label, fx, fy)
      doc.font('Helvetica-Bold').fontSize(9).fillColor(DARK).text(value || '—', fx, fy + 11, { width: colW - 8 })
    })
    y += 132

    // ── SUMMARY STAT BOXES ─────────────────────────────────────────────────
    const statW = (CONTENT_W - 12) / 2
    doc.roundedRect(MARGIN, y, statW, 58, 8).fill(ORANGE_LIGHT)
    doc.roundedRect(MARGIN, y, statW, 58, 8).stroke(ORANGE_BORDER).lineWidth(0.5)
    doc.font('Helvetica-Bold').fontSize(34).fillColor(ORANGE).text(String(required.length), MARGIN + 18, y + 10)
    doc.font('Helvetica-Bold').fontSize(9).fillColor(GRAY_DARK).text('Calibrations', MARGIN + 18 + 36, y + 16)
    doc.font('Helvetica').fontSize(8).fillColor(GRAY_MID).text('Required', MARGIN + 18 + 36, y + 29)

    const sx2 = MARGIN + statW + 12
    doc.roundedRect(sx2, y, statW, 58, 8).fill(GRAY_LIGHT)
    doc.roundedRect(sx2, y, statW, 58, 8).stroke(GRAY_BORDER).lineWidth(0.5)
    doc.font('Helvetica-Bold').fontSize(34).fillColor(GRAY_MID).text(String(notReq.length), sx2 + 18, y + 10)
    doc.font('Helvetica-Bold').fontSize(9).fillColor(GRAY_DARK).text('Calibrations', sx2 + 18 + 36, y + 16)
    doc.font('Helvetica').fontSize(8).fillColor(GRAY_MID).text('Not Required', sx2 + 18 + 36, y + 29)
    y += 74

    // ── CALIBRATION CARD RENDERER ──────────────────────────────────────────
    function drawCal(cal, isRequired) {
      const accentColor = isRequired ? ORANGE      : '#c8c4c0'
      const bgColor     = isRequired ? ORANGE_LIGHT : GRAY_LIGHT
      const borderColor = isRequired ? ORANGE_BORDER: GRAY_BORDER
      const nameColor   = isRequired ? DARK         : '#999'
      const textColor   = isRequired ? GRAY_DARK    : '#aaa'
      const pillBg      = isRequired ? ORANGE       : '#c8c4c0'

      const justH = cal.justification
        ? doc.heightOfString(cal.justification || '', { width: CONTENT_W - 40, fontSize: 8 }) + 12 : 0
      const calLinks = Array.isArray(cal.links) ? cal.links.filter(l => l?.url) : []
      const linksH   = calLinks.length > 0 ? 18 : 0
      const hasChips = cal.cal_type || cal.trigger || cal.line_references
      const rowH = 46 + (hasChips ? 22 : 4) + justH + linksH

      if (y + rowH > PAGE_H - 48) { footer(doc); doc.addPage(); contHeader(doc); y = 52 }

      doc.roundedRect(MARGIN, y, CONTENT_W, rowH, 6).fill(bgColor)
      doc.roundedRect(MARGIN, y, CONTENT_W, rowH, 6).stroke(borderColor).lineWidth(0.5)
      doc.roundedRect(MARGIN, y, 4, rowH, 2).fill(accentColor)

      const pillText = isRequired ? 'REQUIRED' : 'NOT REQUIRED'
      const pillW = doc.widthOfString(pillText, { fontSize: 7 }) + 16
      pill(doc, MARGIN + CONTENT_W - pillW - 10, y + 10, pillText, pillBg, WHITE)

      doc.font('Helvetica-Bold').fontSize(10.5).fillColor(nameColor)
        .text(cal.calibration_name || '—', MARGIN + 14, y + 12, { width: CONTENT_W - pillW - 32 })

      let chipX = MARGIN + 14
      const chipY = y + 32
      if (cal.cal_type)        chipX += chip(doc, chipX, chipY, cal.cal_type,        isRequired ? '#fde8de' : '#e8e5e2', isRequired ? ORANGE : '#999') + 5
      if (cal.trigger)         chipX += chip(doc, chipX, chipY, cal.trigger,         isRequired ? '#fff0eb' : '#e8e5e2', isRequired ? '#a33510' : '#999') + 5
      if (cal.line_references) chip(doc, chipX, chipY, `Lines ${cal.line_references}`, '#e8e5e2', '#777')

      if (cal.justification) {
        const jy = y + (hasChips ? 54 : 36)
        doc.font('Helvetica-Oblique').fontSize(8).fillColor(textColor)
          .text(cal.justification, MARGIN + 14, jy, { width: CONTENT_W - 30 })
      }
      if (calLinks.length > 0) {
        const jy = y + (hasChips ? 54 : 36)
        const afterJustH = cal.justification ? doc.heightOfString(cal.justification, { width: CONTENT_W - 40, fontSize: 8 }) + 6 : 0
        let lx = MARGIN + 14, ly = jy + afterJustH + 2
        calLinks.forEach((link, idx) => {
          const label = link.label || `Reference ${idx + 1}`
          const lw = doc.widthOfString(label, { fontSize: 7.5 }) + 2
          if (lx + lw > MARGIN + CONTENT_W - 20) { lx = MARGIN + 14; ly += 14 }
          doc.font('Helvetica').fontSize(7.5).fillColor(isRequired ? ORANGE : '#aaa')
            .text(label, lx, ly, { link: link.url, underline: true, continued: false, width: lw })
          lx += lw + 14
        })
      }
      y += rowH + 8
    }

    // ── REQUIRED SECTION ──────────────────────────────────────────────────
    if (required.length > 0) {
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor(ORANGE).text('REQUIRED CALIBRATIONS', MARGIN, y)
      doc.font('Helvetica').fontSize(8).fillColor(GRAY_MID)
        .text(`${required.length} calibration${required.length !== 1 ? 's' : ''} identified as required for this vehicle`, MARGIN + 175, y + 0.5)
      y += 18
      required.forEach(cal => drawCal(cal, true))
    }

    // ── NOT REQUIRED SECTION ───────────────────────────────────────────────
    if (notReq.length > 0) {
      if (y + 40 > PAGE_H - 48) { footer(doc); doc.addPage(); contHeader(doc); y = 52 }
      doc.moveTo(MARGIN, y + 6).lineTo(PAGE_W - MARGIN, y + 6).strokeColor(GRAY_BORDER).lineWidth(0.5).stroke()
      y += 20
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor(GRAY_MID).text('NOT REQUIRED', MARGIN, y)
      doc.font('Helvetica').fontSize(8).fillColor(GRAY_MID)
        .text(`${notReq.length} calibration${notReq.length !== 1 ? 's' : ''} reviewed — no triggers identified`, MARGIN + 112, y + 0.5)
      y += 18
      notReq.forEach(cal => drawCal(cal, false))
    }

    // ── DOCUMENT LINKS ─────────────────────────────────────────────────────
    const docLinks = Array.isArray(document_links) ? document_links.filter(l => l?.url) : []
    if (docLinks.length > 0) {
      if (y + 40 > PAGE_H - 48) { footer(doc); doc.addPage(); contHeader(doc); y = 52 }
      doc.moveTo(MARGIN, y + 6).lineTo(PAGE_W - MARGIN, y + 6).strokeColor(GRAY_BORDER).lineWidth(0.5).stroke()
      y += 20
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor(GRAY_MID).text('REFERENCE LINKS', MARGIN, y)
      y += 16
      docLinks.forEach(link => {
        if (y + 16 > PAGE_H - 48) { footer(doc); doc.addPage(); contHeader(doc); y = 52 }
        doc.font('Helvetica').fontSize(8.5).fillColor(ORANGE)
          .text('› ' + (link.label || link.url), MARGIN + 8, y, { link: link.url, underline: true, width: CONTENT_W - 16 })
        y += 16
      })
    }

    footer(doc)
    doc.end()
  })
}
